management/management/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('meetings.urls')),
]

management/meetings/urls.py
from django.urls import path
from . import views

app_name = 'meetings'
urlpatterns = [
    # ex: /meetings/
    #path('', views.IndexView.as_view(), name='index'),
    path('', views.index, name='index'),
    # ex: /meetings/employee/5/
    # path('employee/<int:pk>/', views.EmployeeDetailView.as_view(), name='employee_detail'),
    path('employee/<int:employee_id>/', views.employee_detail, name='employee_detail'),
    # ex: /meetings/meeting/5/
    #path('meeting/<int:pk>/', views.MeetingDetailView.as_view(), name='meeting_detail'),

    path('employees/', views.employees, name='employees'),
    path('employees/<int:employee_id>/edit/', views.employee_edit, name='employee_edit'),

    path('meetings/', views.meetings, name='meetings'),
    path('meetings/<int:meeting_id>/edit/', views.meeting_edit, name='meeting_edit'),
]

management/meetings/models.py
from django.db import models


# Create your models here.
class Employee(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    email = models.EmailField(max_length=254)
    position = models.CharField(max_length=50)

    @property
    def full_name(self):
        """Returns the person's full name."""
        return '%s %s' % (self.first_name, self.last_name)

    def __str__(self):
        return self.full_name


class Relationship(models.Model):
    parent = models.ForeignKey(Employee, on_delete=models.PROTECT, related_name='parent_relationship')
    child = models.ForeignKey(Employee, on_delete=models.PROTECT, related_name='child_relationship')

    def __str__(self):
        return '%s : %s' % (self.parent, self.child)


class Meeting(models.Model):
    ONE_TO_ONE = '121'
    PDR = 'PDR'
    MEETING_TYPE_CHOICES = (
        (ONE_TO_ONE, 'One to One'),
        (PDR, 'PDR'),
    )

    date = models.DateTimeField()
    type = models.CharField(max_length=10, choices=MEETING_TYPE_CHOICES, default=ONE_TO_ONE)
    title = models.CharField(max_length=50)

    def __str__(self):
        return self.title


class EmployeeMeeting(models.Model):
    employee = models.ForeignKey(Employee, on_delete=models.PROTECT)
    meeting = models.ForeignKey(Meeting, on_delete=models.PROTECT)

    def __str__(self):
        return '%s : %s' % (self.employee, self.meeting)


class Note(models.Model):
    meeting = models.ForeignKey(Meeting, on_delete=models.PROTECT)
    text = models.CharField(max_length=200, blank=True, null=True)

    def __str__(self):
        return self.text


class Action(models.Model):
    meeting = models.ForeignKey(Meeting, on_delete=models.PROTECT)
    text = models.CharField(max_length=200, blank=True, null=True)
    employee_to_action = models.ForeignKey(Employee, on_delete=models.PROTECT)
    date_to_be_actioned = models.DateField()

    def __str__(self):
        return self.text

management/meetings/forms.py
from django import forms
from .models import Employee, Meeting, Note

class EmployeeForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = '__all__'

class MeetingForm(forms.ModelForm):
    class Meta:
        model = Meeting
        fields = '__all__'

class NoteForm(forms.ModelForm):
    class Meta:
        model = Note
        fields = ('text',)
        widgets = {
            'text': forms.TextInput(attrs={'disabled': 'true'})
        }

management/meetings/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse
from django.views import generic
from django.forms.models import inlineformset_factory, model_to_dict

from .models import Meeting, Employee, Note, Action
from .forms import EmployeeForm, MeetingForm, NoteForm

'''
class IndexView(generic.ListView):
    template_name = 'meetings/index.html'
    context_object_name = 'latest_meeting_list'

    def get_queryset(self):
        """Return the last five meetings."""
        return Meeting.objects.all()[:5]
'''

def index(request):
    return render(request, 'meetings/index.html')


def employees(request):
    employees = Employee.objects.all()
    return render(request, 'meetings/employees.html', {'employees': employees})


def meetings(request):
    meetings = Meeting.objects.all()
    return render(request, 'meetings/meetings.html', {'meetings': meetings})


def employee_detail(request, employee_id):
    employee = Employee.objects.get(pk=employee_id)
    if request.method == 'POST':
        print('POST')
    else:
        employee_dict = model_to_dict(employee)
        form = EmployeeForm(employee_dict)

        return render(request, 'meetings/employee_detail.html', {'form':form})


def employee_edit(request, employee_id):
    employee = Employee.objects.get(pk=employee_id)
    return redirect(reverse('employees'))


# def meeting_edit(request, meeting_id):
#     meeting = Meeting.objects.get(pk=meeting_id)
#     MeetingInLineFormSet = inlineformset_factory(Meeting, Note, fields=('text',))
#
#     if request.method == 'POST':
#         formset = MeetingInLineFormSet(request.POST, request.FILES, instance=meeting)
#         if formset.is_valid():
#             formset.save()
#             return render(request, 'meetings/index.html')
#     else:
#         formset = MeetingInLineFormSet(instance=meeting)
#     return render(request, 'meetings/meeting_edit.html', {'formset': formset})


def meeting_edit(request, meeting_id):
    if request.method == 'POST':
        meeting = Meeting.objects.get(pk=meeting_id)
        meeting_form = MeetingForm(request.POST, instance=meeting)
        note = Note.objects.get(pk=1)
        note_form = NoteForm(request.POST, instance=note)

        if all([meeting_form.is_valid(), note_form.is_valid()]):
            meeting_form.save()
            note_form.save()
            return redirect(reverse('meetings:meetings'))
    else:
        meeting = Meeting.objects.get(pk=meeting_id)
        meeting_form = MeetingForm(instance=meeting)
        notes = Note.objects.filter(meeting=meeting)
        note_forms = []
        for note in notes:
            note_form = NoteForm(instance=note)
            note_forms.append(note_form)

    return render(request, 'meetings/meeting_edit.html', {
        'meeting_form': meeting_form,
        'note_forms': note_forms,
    })

'''
class EmployeeDetailView(generic.DetailView):
    model = Employee
    template_name = 'meetings/employee_detail.html'
'''
class MeetingDetailView(generic.DetailView):
    model = Meeting
    template_name = 'meetings/meeting_detail.html'

management/meetings/templates/meetings/employee_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Employee Details</title>
</head>
<body>
    <h1>Employee Details</h1>
    {{ employee.first_name }}
</body>
</html>

management/meetings/templates/meetings/employees.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Employees</title>
</head>
<body>
    <h1>Your Employees:</h1>
    {% if employees %}
        <table class="table">
            <thead>
              <tr>
                <th>Name</th>
                <th>Position</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              {% for employee in employees %}
              <tr>
                <td>{{ employee }}</td>
                <td>{{ employee.position }}</td>
                <td>
                    <a href="{% url 'meetings:employee_edit' employee.id %}">Edit</a>
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
    {% else %}
        <p>You do not have any Employees under your direct line management.</p>
    {% endif %}

</body>
</html>

management/meetings/templates/meetings/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'meetings/style.css' %}">

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Home Page</title>
</head>
<body>
    <h1>Home Page</h1>
        <ul>
            <li><a href="{% url 'meetings:meetings' %}">Your Meetings</a></li>
            <li><a href="{% url 'meetings:employees' %}">Your Employees</a></li>
        </ul>

</body>
</html>

management/meetings/templates/meetings/meeting_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Meeting Details</title>
</head>
<body>
    <h1>Meeting Details</h1>
    {{ meeting }}
    {{ meeting.date }}
    {{ meeting.type }}
</body>
</html>

management/meetings/templates/meetings/meeting_edit.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'meetings/style.css' %}">

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js" type="application/javascript"></script>
    <script>
    $(document).ready(function() {

        $(".edit-button").on("click", function(e) {
            var t = this.closest("tr").children[0].children[0].children[1];
            t.disabled = false;

            var saveButton = this.closest("tr").children[3].children[0];
            saveButton.className = "visible-save-button";
        });

        $(".invisible-save-button").on("click", function(e) {
            this.className = "invisible-save-button";
            var t = this.closest("tr").children[0].children[0].children[1];
            t.disabled = true;
        });
    });
    </script>
    <title>Your Meetings</title>
</head>
<body>
    <h1>Meeting:</h1>

    <form method="post">
        {% csrf_token %}
        {{ meeting_form.as_p }}
    <input type="submit" value="Submit">
    <a href="{% url 'meetings:meetings' %}"
       class="btn" role="button">Back to Meetings</a>
    </form>

    <h2>Meeting Notes:</h2>

        <table class="table">
            <tbody>
              {% for note_form in note_forms %}
              <tr>
                <td>{{ note_form.as_p }}</td>
                <td>
                    <button type="button" class="edit-button">Edit Note</button>
                </td>
                <td>
                    <button type="button" onclick="alert('Delete Note')">Delete Note</button>
                </td>
                  <td>
                    <button type="button" class="invisible-save-button">Save Note</button>
                  </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
    <br>
    <button type="button" onclick="alert('Add Note')">Add Note</button>

</body>
</html>

management/meetings/templates/meetings/meetings.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Your Meetings</title>
</head>
<body>
    <h1>Your Meetings:</h1>
    {% if meetings %}
        <table class="table">
            <thead>
              <tr>
                <th>Date</th>
                <th>Type</th>
                <th>Title</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              {% for meeting in meetings %}
              <tr>
                <td>{{ meeting.date }}</td>
                <td>{{ meeting.type }}</td>
                <td>{{ meeting.title }}</td>
                <td>
                    <a href="{% url 'meetings:meeting_edit' meeting.id %}">Edit</a>
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
    {% else %}
        <p>You do not have any Meetings.</p>
    {% endif %}

</body>
</html>